services:
  db:
    image: mariadb:11.4
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - pfadfinder_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: nextcloud:33
    restart: always
    volumes:
      - nextcloud_app:/var/www/html
      - ${NEXTCLOUD_DATA_DIR:-nextcloud_userdata}:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${DOMAIN_NAME}
    networks:
      - pfadfinder_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      # Die Nextcloud ist unter `cloud.eure-domain.de` erreichbar
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.middlewares=security-headers@docker"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

volumes:
  db_data:
  nextcloud_app:
  nextcloud_userdata:

networks:
  pfadfinder_net:
    external: true
